export type DtcReference = { code: string; title: string; meaning: string; causes: string[]; tests: string[]; warning: string };

const references: Record<string, DtcReference> = {
  C1208: { code: "C1208", title: "Circuito/sinal do sensor de velocidade da roda", meaning: "Em veículos Hyundai, este código normalmente está relacionado ao sinal do sensor de velocidade de uma das rodas no sistema ABS. A descrição exata e a posição da roda devem ser confirmadas no scanner e no manual da versão.", causes: ["Sensor de velocidade da roda sujo, danificado ou com folga", "Chicote rompido, em curto ou com mau contato", "Conector oxidado ou com entrada de água", "Anel magnético/roda fônica danificado", "Folga no rolamento ou falha no módulo ABS"], tests: ["Ler todos os códigos do módulo ABS e identificar a roda indicada", "Comparar em tempo real a velocidade das quatro rodas no scanner", "Inspecionar sensor, conector, chicote e anel magnético", "Testar alimentação, aterramento e sinal conforme o diagrama", "Apagar o código depois do reparo e realizar teste de rodagem seguro"], warning: "Falhas no ABS podem desativar assistências de frenagem. Confirme a roda e o circuito indicados pelo scanner antes de substituir peças." },
  P0300: { code: "P0300", title: "Falha de combustão aleatória ou múltipla", meaning: "A central detectou falhas de combustão em mais de um cilindro.", causes: ["Velas ou bobinas", "Injetores ou pressão de combustível", "Entrada falsa de ar", "Baixa compressão ou sincronismo"], tests: ["Consultar contadores de falha por cilindro", "Inspecionar velas e permutar bobinas", "Testar injetores e pressão", "Verificar compressão e sincronismo"], warning: "Se a luz de injeção estiver piscando, evite circular para não danificar o catalisador." },
  P0171: { code: "P0171", title: "Mistura pobre — banco 1", meaning: "A correção de combustível atingiu o limite positivo no banco 1.", causes: ["Entrada falsa de ar", "Baixa pressão de combustível", "MAF incorreto", "Injetores com baixa vazão"], tests: ["Analisar STFT e LTFT", "Fazer teste de fumaça na admissão", "Medir pressão de combustível", "Avaliar MAF e sonda"], warning: "Confirme os dados específicos do motor antes de substituir componentes." },
  P0420: { code: "P0420", title: "Eficiência do catalisador abaixo do limite", meaning: "O monitor detectou baixa eficiência do catalisador no banco 1.", causes: ["Catalisador degradado", "Falha de combustão ou mistura", "Vazamento no escape", "Sondas lambda"], tests: ["Corrigir primeiro falhas de ignição e mistura", "Inspecionar vazamentos", "Comparar sinais das sondas", "Avaliar temperatura e contrapressão"], warning: "Não condene o catalisador sem testar as causas que podem tê-lo danificado." },
};

export function findDtcReference(code: string) { return references[code.trim().toUpperCase()] || null; }
export function formatDtcReference(reference: DtcReference, vehicle?: string) { return [`${reference.code} — ${reference.title}`, vehicle ? `Veículo: ${vehicle}` : "", "", "Significado", reference.meaning, "", "Causas prováveis", ...reference.causes.map((item, index) => `${index + 1}. ${item}`), "", "Testes recomendados", ...reference.tests.map((item, index) => `${index + 1}. ${item}`), "", "Atenção", reference.warning].filter(Boolean).join("\n"); }
