import { createClient as createAdminClient } from "@supabase/supabase-js";
import webpush from "web-push";
import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
export const runtime = "nodejs";
type Subscription = { endpoint: string; p256dh: string; auth: string };
const labels: Record<string, string> = { open: "O.S. aberta", diagnosing: "Veiculo em diagnostico", awaiting_approval: "Orcamento disponivel", awaiting_part: "Aguardando peca", repairing: "Veiculo em reparo", finished: "CARRO PRONTO PARA RETIRADA", delivered: "Veiculo entregue", cancelled: "O.S. cancelada" };
function admin() { return createAdminClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, { auth: { autoRefreshToken: false, persistSession: false } }); }
async function send(rows: Subscription[], title: string, body: string, url: string) { webpush.setVapidDetails("mailto:suporte@crconnect.app", process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY!, process.env.VAPID_PRIVATE_KEY!); await Promise.all(rows.map(async (row) => { try { await webpush.sendNotification({ endpoint: row.endpoint, keys: { p256dh: row.p256dh, auth: row.auth } }, JSON.stringify({ title, body, url })); } catch (error) { const status = (error as { statusCode?: number }).statusCode; if (status === 404 || status === 410) await admin().from("push_subscriptions").delete().eq("endpoint", row.endpoint); } })); }
export async function POST(request: Request) { if (!process.env.SUPABASE_SERVICE_ROLE_KEY || !process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY || !process.env.VAPID_PRIVATE_KEY) return NextResponse.json({ error: "Push not configured" }, { status: 503 }); const { id, event } = await request.json() as { id?: string; event?: "request" | "status" }; const session = await createClient(); const { data: { user } } = await session.auth.getUser(); if (!id || !event || !user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); const db = admin(); if (event === "request") { const { data: item } = await db.from("service_requests").select("workshop_id,owner_id").eq("id", id).maybeSingle(); if (!item || item.owner_id !== user.id) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const { data: members } = await db.from("workshop_users").select("user_id").eq("workshop_id", item.workshop_id); const ids = (members || []).map((member) => member.user_id); const { data: rows } = ids.length ? await db.from("push_subscriptions").select("endpoint,p256dh,auth").in("user_id", ids) : { data: [] as Subscription[] }; await send((rows || []) as Subscription[], "Nova solicitacao de O.S.", "Um cliente abriu uma solicitacao de atendimento.", "/app/ordens"); return NextResponse.json({ ok: true }); } const { data: order } = await db.from("service_orders").select("id,workshop_id,owner_id,number,status").eq("id", id).maybeSingle(); if (!order || !order.owner_id) return NextResponse.json({ ok: true }); const { data: membership } = await db.from("workshop_users").select("user_id").eq("workshop_id", order.workshop_id).eq("user_id", user.id).maybeSingle(); if (!membership) return NextResponse.json({ error: "Forbidden" }, { status: 403 }); const { data: rows } = await db.from("push_subscriptions").select("endpoint,p256dh,auth").eq("user_id", order.owner_id); await send((rows || []) as Subscription[], labels[order.status] || "O.S. atualizada", "Sua Ordem de Servico #" + order.number + " foi atualizada.", "/app/minhas-os"); return NextResponse.json({ ok: true }); }
