"use client";

import { ChangeEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Attachment = { id: string; file_name: string; mime_type: string; size_bytes: number; storage_path: string; url?: string };
const bucket = "workshop-attachments";

export function AttachmentsManager({ workshopId, orderId }: { workshopId: string; orderId: string }) {
  const db = createClient(); const [items, setItems] = useState<Attachment[]>([]); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  async function load() { const { data } = await db.from("attachments").select("id,file_name,mime_type,size_bytes,storage_path").eq("workshop_id", workshopId).eq("service_order_id", orderId).order("created_at", { ascending: false }); const withUrls = await Promise.all((data || []).map(async item => { const { data: signed } = await db.storage.from(bucket).createSignedUrl(item.storage_path, 3600); return { ...item, url: signed?.signedUrl }; })); setItems(withUrls); }
  useEffect(() => { load(); }, [orderId]);
  async function upload(e: ChangeEvent<HTMLInputElement>) { const file = e.target.files?.[0]; if (!file) return; if (file.size > 10 * 1024 * 1024) { setMessage("O arquivo deve ter no máximo 10 MB."); return; } setLoading(true); const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, "-"); const path = `${workshopId}/orders/${orderId}/${crypto.randomUUID()}-${safeName}`; const { error: uploadError } = await db.storage.from(bucket).upload(path, file, { contentType: file.type }); if (uploadError) { setMessage(uploadError.message); setLoading(false); return; } const { error } = await db.from("attachments").insert({ workshop_id: workshopId, service_order_id: orderId, storage_path: path, file_name: file.name, mime_type: file.type || "application/octet-stream", size_bytes: file.size }); if (error) { await db.storage.from(bucket).remove([path]); setMessage(error.message); } else { setMessage("Arquivo enviado com sucesso."); load(); } setLoading(false); e.target.value = ""; }
  async function remove(item: Attachment) { if (!confirm(`Remover ${item.file_name}?`)) return; await db.storage.from(bucket).remove([item.storage_path]); await db.from("attachments").delete().eq("id", item.id); load(); }
  return <section className="mt-5 rounded-xl border border-zinc-800 bg-black/40 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold tracking-[.16em] text-[#FFC107]">FOTOS E ANEXOS</p><p className="mt-1 text-xs text-zinc-500">Imagens e arquivos de até 10 MB, privados para sua oficina.</p></div><label className="cursor-pointer rounded-lg border border-[#FFC107] px-3 py-2 text-sm font-bold text-[#FFC107] hover:bg-[#261e0b]">{loading ? "Enviando..." : "Adicionar arquivo"}<input disabled={loading} type="file" accept="image/*,.pdf" className="hidden" onChange={upload} /></label></div>{message && <p className="mt-3 text-sm text-zinc-300">{message}</p>}<div className="mt-4 grid gap-3 sm:grid-cols-2">{items.map(item => <article key={item.id} className="overflow-hidden rounded-lg border border-zinc-800 bg-zinc-900"><>{item.mime_type.startsWith("image/") && item.url ? <img src={item.url} alt={item.file_name} className="h-32 w-full object-cover" /> : <div className="grid h-24 place-items-center text-2xl">PDF</div>}</><div className="flex items-center justify-between gap-2 p-3"><a className="truncate text-sm text-[#FFC107] underline" href={item.url} target="_blank" rel="noreferrer">{item.file_name}</a><button onClick={() => remove(item)} className="text-xs text-red-300">Remover</button></div></article>)}{items.length === 0 && <p className="text-sm text-zinc-500">Nenhum anexo nesta O.S.</p>}</div></section>;
}
