"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { PrintDocument } from "@/components/print-document";

type Client = { id: string; full_name: string }; type Vehicle = { id: string; client_id: string; brand: string; model: string }; type Budget = { id: string; status: string; clients: Client | null; vehicles: Vehicle | null }; type Item = { id: string; description: string; kind: string; quantity: number; unit_price: number; discount: number };
const states = [["draft", "Rascunho"], ["sent", "Enviado"], ["approved", "Aprovado"], ["rejected", "Recusado"], ["expired", "Expirado"]];

export function BudgetsManager({ workshopId }: { workshopId: string }) {
  const db = createClient(); const [clients, setClients] = useState<Client[]>([]); const [vehicles, setVehicles] = useState<Vehicle[]>([]); const [budgets, setBudgets] = useState<Budget[]>([]); const [selected, setSelected] = useState<Budget | null>(null); const [items, setItems] = useState<Item[]>([]); const [client, setClient] = useState(""); const [vehicle, setVehicle] = useState(""); const [status, setStatus] = useState("draft"); const [description, setDescription] = useState(""); const [price, setPrice] = useState("0"); const [message, setMessage] = useState("");
  async function load() { const [a, b, c] = await Promise.all([db.from("clients").select("id,full_name").eq("workshop_id", workshopId), db.from("vehicles").select("id,client_id,brand,model").eq("workshop_id", workshopId), db.from("budgets").select("id,status,clients(id,full_name),vehicles(id,client_id,brand,model)").eq("workshop_id", workshopId).order("created_at", { ascending: false })]); setClients((a.data || []) as Client[]); setVehicles((b.data || []) as Vehicle[]); setBudgets((c.data || []) as unknown as Budget[]); }
  async function loadItems(id: string) { const { data } = await db.from("budget_items").select("id,description,kind,quantity,unit_price,discount").eq("workshop_id", workshopId).eq("budget_id", id); setItems((data || []) as Item[]); }
  useEffect(() => { load(); }, []); const allowed = vehicles.filter(v => v.client_id === client); const total = useMemo(() => items.reduce((sum, item) => sum + Number(item.quantity) * Number(item.unit_price) - Number(item.discount), 0), [items]);
  async function create(e: FormEvent) { e.preventDefault(); const { data, error } = await db.from("budgets").insert({ workshop_id: workshopId, client_id: client, vehicle_id: vehicle, status }).select("id,status,clients(id,full_name),vehicles(id,client_id,brand,model)").single(); if (error) setMessage(error.message); else { const budget = data as unknown as Budget; setSelected(budget); setItems([]); setMessage("Orçamento criado. Agora adicione os itens."); load(); } }
  async function add(e: FormEvent) { e.preventDefault(); if (!selected) return; const { error } = await db.from("budget_items").insert({ workshop_id: workshopId, budget_id: selected.id, kind: "service", description, quantity: 1, unit_price: Number(price), discount: 0 }); if (error) setMessage(error.message); else { setDescription(""); setPrice("0"); loadItems(selected.id); } }
  function choose(budget: Budget) { setSelected(budget); setItems([]); loadItems(budget.id); }
  return <div className="grid gap-8 xl:grid-cols-[380px_1fr]"><form onSubmit={create} className="rounded-xl border border-zinc-800 bg-[#1A1A1A] p-5"><h2 className="font-semibold">Novo orçamento</h2><div className="mt-4 grid gap-3"><select required className="field" value={client} onChange={e => { setClient(e.target.value); setVehicle(""); }}><option value="">Cliente *</option>{clients.map(item => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select><select required className="field" disabled={!client} value={vehicle} onChange={e => setVehicle(e.target.value)}><option value="">Veículo *</option>{allowed.map(item => <option key={item.id} value={item.id}>{item.brand} {item.model}</option>)}</select><select className="field" value={status} onChange={e => setStatus(e.target.value)}>{states.map(item => <option key={item[0]} value={item[0]}>{item[1]}</option>)}</select></div><button className="mt-4 rounded-lg bg-[#FFC107] px-4 py-2 font-bold text-black">Criar orçamento</button>{message && <p className="mt-3 text-sm text-zinc-300">{message}</p>}</form><section><h2 className="text-xl font-semibold">Orçamentos</h2><div className="mt-3 space-y-2">{budgets.map(budget => <button key={budget.id} onClick={() => choose(budget)} className="flex w-full justify-between rounded-lg border border-zinc-800 p-3 text-left hover:border-[#FFC107]"><span>{budget.clients?.full_name} · {budget.vehicles?.brand} {budget.vehicles?.model}</span><b className="text-[#FFC107]">{states.find(item => item[0] === budget.status)?.[1]}</b></button>)}</div>{selected && <div className="mt-5 rounded-xl border border-zinc-800 bg-[#1A1A1A] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">Itens e valores</h3><PrintDocument type="Orçamento" number={selected.id.slice(0, 8).toUpperCase()} client={selected.clients?.full_name || "Cliente"} vehicle={`${selected.vehicles?.brand || ""} ${selected.vehicles?.model || ""}`} status={states.find(item => item[0] === selected.status)?.[1] || selected.status} items={items} /></div><form onSubmit={add} className="mt-3 flex gap-2"><input required className="field" placeholder="Serviço, peça ou mão de obra" value={description} onChange={e => setDescription(e.target.value)} /><input required className="field w-28" type="number" step="0.01" value={price} onChange={e => setPrice(e.target.value)} /><button className="rounded-lg bg-[#FFC107] px-3 font-bold text-black">Adicionar</button></form>{items.map(item => <div key={item.id} className="mt-2 flex justify-between rounded bg-zinc-900 p-2 text-sm"><span>{item.description}</span><b>R$ {(Number(item.quantity) * Number(item.unit_price) - Number(item.discount)).toFixed(2)}</b></div>)}<p className="mt-4 text-right text-lg font-bold text-[#FFC107]">Total: R$ {total.toFixed(2)}</p></div>}</section></div>;
}
