"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Client = { id: string; full_name: string; document_number: string | null; phone: string | null; whatsapp: string | null; email: string | null; notes: string | null };
const empty = { full_name: "", document_number: "", phone: "", whatsapp: "", email: "", notes: "" };

export function ClientsManager({ workshopId }: { workshopId: string }) {
  const [items, setItems] = useState<Client[]>([]); const [form, setForm] = useState(empty); const [editing, setEditing] = useState<string | null>(null); const [query, setQuery] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function load() { const { data, error } = await createClient().from("clients").select("id,full_name,document_number,phone,whatsapp,email,notes").eq("workshop_id", workshopId).order("full_name"); if (error) setMessage(error.message); else setItems((data || []) as Client[]); }
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => items.filter((item) => `${item.full_name} ${item.document_number || ""} ${item.phone || ""}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  function change(key: keyof typeof empty, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); const payload = { workshop_id: workshopId, full_name: form.full_name.trim(), document_number: form.document_number.replace(/\D/g, "") || null, phone: form.phone.trim() || null, whatsapp: form.whatsapp.trim() || null, email: form.email.trim() || null, notes: form.notes.trim() || null }; const db = createClient(); const result = editing ? await db.from("clients").update(payload).eq("id", editing).eq("workshop_id", workshopId) : await db.from("clients").insert(payload); if (result.error) { setMessage(result.error.code === "23505" ? "Já existe um cliente com este CPF nesta oficina." : result.error.message); setSaving(false); return; } window.location.assign("/app"); }
  function edit(item: Client) { setEditing(item.id); setForm({ full_name: item.full_name, document_number: item.document_number || "", phone: item.phone || "", whatsapp: item.whatsapp || "", email: item.email || "", notes: item.notes || "" }); }
  async function remove(id: string) { if (!confirm("Excluir este cliente? Veículos e O.S. vinculados impedem a exclusão.")) return; const { error } = await createClient().from("clients").delete().eq("id", id).eq("workshop_id", workshopId); setMessage(error ? error.message : "Cliente excluído."); if (!error) await load(); }
  return <div className="grid gap-8 xl:grid-cols-[390px_1fr]"><form onSubmit={submit} className="h-fit rounded-xl border border-zinc-800 bg-[#1A1A1A] p-5"><h2 className="font-semibold">{editing ? "Editar cliente" : "Novo cliente"}</h2><div className="mt-4 grid gap-3"><input required value={form.full_name} onChange={(event) => change("full_name", event.target.value)} placeholder="Nome completo *" className="field"/><input value={form.document_number} onChange={(event) => change("document_number", event.target.value)} inputMode="numeric" placeholder="CPF" className="field"/><input value={form.phone} onChange={(event) => change("phone", event.target.value)} placeholder="Telefone" className="field"/><input value={form.whatsapp} onChange={(event) => change("whatsapp", event.target.value)} placeholder="WhatsApp" className="field"/><input value={form.email} onChange={(event) => change("email", event.target.value)} type="email" placeholder="E-mail" className="field"/><textarea value={form.notes} onChange={(event) => change("notes", event.target.value)} placeholder="Observações" className="field min-h-24"/></div><div className="mt-4 flex gap-2"><button disabled={saving} className="rounded-lg bg-[#FFC107] px-4 py-2 font-bold text-black disabled:opacity-60">{saving ? "Salvando..." : "Salvar e voltar"}</button>{editing && <button type="button" onClick={() => { setEditing(null); setForm(empty); }} className="rounded-lg border border-zinc-700 px-4 py-2">Cancelar</button>}</div>{message && <p className="mt-3 text-sm text-zinc-300">{message}</p>}</form><section><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold">Clientes</h2><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar nome, CPF ou telefone" className="field max-w-xs"/></div><div className="mt-4 overflow-hidden rounded-xl border border-zinc-800"><table className="w-full text-left text-sm"><thead className="bg-[#1A1A1A] text-zinc-400"><tr><th className="p-3">Cliente</th><th className="p-3">Contato</th><th className="p-3"/></tr></thead><tbody>{filtered.map((item) => <tr key={item.id} className="border-t border-zinc-800"><td className="p-3"><strong>{item.full_name}</strong><br/><span className="text-zinc-500">{item.document_number || "CPF não informado"}</span></td><td className="p-3 text-zinc-400">{item.whatsapp || item.phone || item.email || "—"}</td><td className="p-3 text-right"><button type="button" onClick={() => edit(item)} className="mr-3 text-[#FFC107]">Editar</button><button type="button" onClick={() => void remove(item.id)} className="text-red-400">Excluir</button></td></tr>)}{filtered.length === 0 && <tr><td colSpan={3} className="p-8 text-center text-zinc-500">Nenhum cliente encontrado.</td></tr>}</tbody></table></div></section></div>;
}
