"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Dtc = { id: string; workshop_id: string | null; code: string; title: string; description: string | null; possible_causes: string | null; recommended_tests: string | null };
type Tech = { id: string; workshop_id: string | null; title: string; category: string; brand: string | null; model: string | null; engine: string | null; content: string; source_url: string | null };

const commonDtcs: Dtc[] = [
  { id: "builtin-p0101", workshop_id: null, code: "P0101", title: "Faixa/desempenho do sensor MAF", description: "O fluxo de ar medido está fora da faixa esperada pela ECU.", possible_causes: "Sensor MAF sujo ou defeituoso; entrada falsa de ar; filtro obstruído; chicote ou conector.", recommended_tests: "Inspecionar admissão e mangueiras; conferir filtro; analisar leitura do MAF; testar alimentação e aterramento." },
  { id: "builtin-p0113", workshop_id: null, code: "P0113", title: "Sinal alto do sensor de temperatura do ar", description: "A ECU detectou tensão alta no circuito IAT.", possible_causes: "Sensor IAT desconectado; circuito aberto; conector oxidado; sensor defeituoso.", recommended_tests: "Inspecionar conector; comparar IAT com temperatura ambiente; testar continuidade e resistência conforme o manual." },
  { id: "builtin-p0128", workshop_id: null, code: "P0128", title: "Temperatura do líquido abaixo do esperado", description: "O motor demora demais para atingir a temperatura de trabalho.", possible_causes: "Válvula termostática travada aberta; sensor ECT; nível baixo; sistema de arrefecimento.", recommended_tests: "Verificar nível e vazamentos com motor frio; acompanhar ECT; testar a válvula termostática." },
  { id: "builtin-p0171", workshop_id: null, code: "P0171", title: "Mistura pobre — banco 1", description: "A correção de combustível atingiu limite positivo no banco 1.", possible_causes: "Entrada falsa de ar; baixa pressão; injetores; MAF; vazamento no escape antes da sonda.", recommended_tests: "Analisar STFT/LTFT; testar fumaça na admissão; medir pressão; avaliar MAF e sonda." },
  { id: "builtin-p0172", workshop_id: null, code: "P0172", title: "Mistura rica — banco 1", description: "A correção de combustível atingiu limite negativo no banco 1.", possible_causes: "Injetor com fuga; pressão alta; filtro de ar; MAF; sensor ECT; sonda lambda.", recommended_tests: "Analisar correções e sonda; medir pressão; testar injetores; conferir MAF e ECT." },
  { id: "builtin-p0300", workshop_id: null, code: "P0300", title: "Falha de combustão aleatória ou múltipla", description: "A ECU detectou falhas de combustão em mais de um cilindro.", possible_causes: "Velas; bobinas; injetores; combustível; entrada falsa de ar; compressão; sincronismo.", recommended_tests: "Consultar contadores de misfire; inspecionar velas; permutar bobinas; testar injetores, pressão, compressão e sincronismo." },
  { id: "builtin-p0301", workshop_id: null, code: "P0301", title: "Falha de combustão no cilindro 1", description: "Falha de combustão concentrada no cilindro 1.", possible_causes: "Vela; bobina; injetor; chicote; compressão; entrada de ar localizada.", recommended_tests: "Permutar vela e bobina; verificar pulso do injetor; realizar teste de compressão e estanqueidade." },
  { id: "builtin-p0325", workshop_id: null, code: "P0325", title: "Circuito do sensor de detonação", description: "Falha elétrica ou sinal incoerente no sensor de detonação.", possible_causes: "Sensor; torque incorreto; chicote; conector; ruído mecânico.", recommended_tests: "Inspecionar sensor e chicote; conferir fixação conforme manual; avaliar sinal e ruídos mecânicos." },
  { id: "builtin-p0420", workshop_id: null, code: "P0420", title: "Eficiência do catalisador abaixo do limite", description: "O monitor detectou baixa eficiência do catalisador no banco 1.", possible_causes: "Catalisador degradado; misfire; consumo de óleo; vazamento no escape; sondas.", recommended_tests: "Corrigir misfire e mistura; inspecionar vazamentos; comparar sondas; avaliar temperatura e contrapressão." },
  { id: "builtin-p0500", workshop_id: null, code: "P0500", title: "Falha no sinal de velocidade do veículo", description: "A ECU não recebe um sinal de velocidade válido.", possible_causes: "Sensor de velocidade; sensor ABS; chicote; rolamento magnético; módulo ABS.", recommended_tests: "Comparar velocidades das rodas; inspecionar sensores, anéis e chicotes; verificar comunicação ABS." },
  { id: "builtin-p0562", workshop_id: null, code: "P0562", title: "Tensão baixa do sistema", description: "A tensão de alimentação ficou abaixo do limite.", possible_causes: "Bateria; alternador; correia; terminais; aterramentos; consumo parasita.", recommended_tests: "Testar bateria e carga; medir queda de tensão; verificar correia, terminais e aterramentos." },
  { id: "builtin-p0700", workshop_id: null, code: "P0700", title: "Solicitação de falha da transmissão", description: "O módulo da transmissão solicitou o acendimento da luz de avaria.", possible_causes: "Outro código armazenado no TCM; falha de comunicação ou alimentação.", recommended_tests: "Acessar o TCM com scanner compatível e diagnosticar os códigos específicos." },
];

const emptyForm = { code: "", title: "", category: "", brand: "", model: "", engine: "", description: "", causes: "", tests: "", content: "", sourceUrl: "" };

export function DiagnosticLibrary({ workshopId, mode }: { workshopId: string; mode: "dtc" | "tech" }) {
  const db = useMemo(() => createClient(), []);
  const [dtcs, setDtcs] = useState<Dtc[]>([]); const [tech, setTech] = useState<Tech[]>([]); const [q, setQ] = useState(""); const [searched, setSearched] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false); const [form, setForm] = useState(emptyForm);
  const isDtc = mode === "dtc";

  const load = useCallback(async () => {
    setLoading(true); setError("");
    if (mode === "dtc") {
      const result = await db.from("dtcs").select("id,workshop_id,code,title,description,possible_causes,recommended_tests").or(`workshop_id.is.null,workshop_id.eq.${workshopId}`).order("code");
      if (result.error) setError(`Não foi possível carregar a base online: ${result.error.message}`);
      setDtcs((result.data || []) as Dtc[]);
    } else {
      const result = await db.from("technical_data").select("id,workshop_id,title,category,brand,model,engine,content,source_url").or(`workshop_id.is.null,workshop_id.eq.${workshopId}`).order("title");
      if (result.error) setError(`Não foi possível carregar a biblioteca: ${result.error.message}`);
      setTech((result.data || []) as Tech[]);
    }
    setLoading(false);
  }, [db, mode, workshopId]);
  useEffect(() => { void load(); }, [load]);

  const availableDtcs = useMemo(() => { const byCode = new Map(commonDtcs.map((item) => [item.code, item])); dtcs.forEach((item) => byCode.set(item.code.toUpperCase(), item)); return [...byCode.values()].sort((a, b) => a.code.localeCompare(b.code)); }, [dtcs]);
  const normalized = q.trim().toLocaleLowerCase("pt-BR");
  const results = isDtc ? availableDtcs.filter((x) => `${x.code} ${x.title} ${x.description || ""} ${x.possible_causes || ""}`.toLocaleLowerCase("pt-BR").includes(normalized)) : tech.filter((x) => `${x.title} ${x.category} ${x.brand || ""} ${x.model || ""} ${x.engine || ""} ${x.content}`.toLocaleLowerCase("pt-BR").includes(normalized));

  function update(key: keyof typeof emptyForm, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  async function save(event: FormEvent) {
    event.preventDefault(); setSaving(true); setNotice(""); setError("");
    const result = isDtc ? await db.from("dtcs").insert({ workshop_id: workshopId, code: form.code.trim().toUpperCase(), title: form.title.trim(), description: form.description.trim() || null, possible_causes: form.causes.trim() || null, recommended_tests: form.tests.trim() || null }) : await db.from("technical_data").insert({ workshop_id: workshopId, category: form.category.trim(), title: form.title.trim(), brand: form.brand.trim() || null, model: form.model.trim() || null, engine: form.engine.trim() || null, content: form.content.trim(), source_url: form.sourceUrl.trim() || null });
    setSaving(false); if (result.error) { setError(`Não foi possível salvar: ${result.error.message}`); return; }
    setNotice(isDtc ? "Código DTC salvo na base da oficina." : "Procedimento salvo na Biblioteca Técnica."); setForm(emptyForm); setShowForm(false); await load();
  }

  return <section className="rounded-2xl border border-zinc-800 bg-[#1A1A1A] p-5">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{isDtc ? "Buscar código DTC" : "Buscar na Biblioteca Técnica"}</h2><p className="mt-1 text-sm text-zinc-400">{isDtc ? "Consulte pelo código, descrição ou sintoma." : "Pesquise procedimento, marca, modelo, motor ou categoria."}</p></div><button type="button" onClick={() => setShowForm((open) => !open)} className="rounded-lg border border-[#FFC107]/70 px-4 py-2 text-sm font-bold text-[#FFC107]">{showForm ? "Fechar cadastro" : isDtc ? "+ Cadastrar DTC" : "+ Novo procedimento"}</button></div>
    {showForm && <form onSubmit={save} className="mt-5 grid gap-3 rounded-xl border border-[#6b510d] bg-black/25 p-4 sm:grid-cols-2"><h3 className="font-bold text-[#FFC107] sm:col-span-2">{isDtc ? "Referência DTC da oficina" : "Novo procedimento técnico"}</h3>{isDtc ? <><input required className="field" placeholder="Código (ex.: P0302)" value={form.code} onChange={(e) => update("code", e.target.value)} /><input required className="field" placeholder="Título" value={form.title} onChange={(e) => update("title", e.target.value)} /><textarea className="field sm:col-span-2" placeholder="Descrição" value={form.description} onChange={(e) => update("description", e.target.value)} /><textarea className="field" placeholder="Causas possíveis" value={form.causes} onChange={(e) => update("causes", e.target.value)} /><textarea className="field" placeholder="Testes recomendados" value={form.tests} onChange={(e) => update("tests", e.target.value)} /></> : <><input required className="field" placeholder="Título do procedimento" value={form.title} onChange={(e) => update("title", e.target.value)} /><input required className="field" placeholder="Categoria" value={form.category} onChange={(e) => update("category", e.target.value)} /><input className="field" placeholder="Marca" value={form.brand} onChange={(e) => update("brand", e.target.value)} /><input className="field" placeholder="Modelo" value={form.model} onChange={(e) => update("model", e.target.value)} /><input className="field" placeholder="Motor" value={form.engine} onChange={(e) => update("engine", e.target.value)} /><input className="field" type="url" placeholder="Fonte ou manual (URL)" value={form.sourceUrl} onChange={(e) => update("sourceUrl", e.target.value)} /><textarea required className="field min-h-36 sm:col-span-2" placeholder="Passo a passo, especificações e cuidados" value={form.content} onChange={(e) => update("content", e.target.value)} /></>}<button disabled={saving} className="rounded-lg bg-[#FFC107] px-5 py-3 font-bold text-black disabled:opacity-60 sm:col-span-2">{saving ? "Salvando..." : "Salvar na base da oficina"}</button></form>}
    <form onSubmit={(event) => { event.preventDefault(); setSearched(true); }} className="mt-5 flex flex-col gap-3 sm:flex-row"><input required className="field flex-1" placeholder={isDtc ? "Ex.: P0300 ou falha de ignição" : "Ex.: correia dentada, Sportage, motor 2.0..."} value={q} onChange={(e) => { setQ(e.target.value); setSearched(false); }} /><button className="rounded-lg bg-[#FFC107] px-5 py-2 font-bold text-black">Buscar</button></form>
    {loading && <p className="mt-4 text-sm text-zinc-400">Carregando referências...</p>}{error && <p role="alert" className="mt-4 rounded-lg border border-red-500/50 bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}{notice && <p role="status" className="mt-4 rounded-lg border border-emerald-500/50 bg-emerald-500/10 p-3 text-sm text-emerald-300">{notice}</p>}
    {searched && <p className="mt-4 text-sm text-[#FFC107]">{results.length ? `${results.length} resultado(s) encontrado(s).` : "Nenhuma referência encontrada. Cadastre uma referência ou tente outros termos."}</p>}
    {!isDtc && !loading && tech.length === 0 && !searched && <p className="mt-5 rounded-xl border border-dashed border-zinc-700 p-4 text-sm text-zinc-400">A biblioteca ainda não possui procedimentos. Use <b className="text-[#FFC107]">+ Novo procedimento</b> para criar o primeiro.</p>}
    <div className="mt-5 space-y-3">{searched && results.map((item) => <article key={item.id} className="rounded-xl border border-zinc-800 bg-[#111] p-4">{isDtc ? <DtcResult item={item as Dtc} /> : <TechResult item={item as Tech} />}</article>)}</div>
  </section>;
}

function DtcResult({ item }: { item: Dtc }) { return <><div className="flex flex-wrap items-center justify-between gap-2"><b className="text-lg text-[#FFC107]">{item.code}</b><span className="rounded-full bg-zinc-800 px-3 py-1 text-[11px] font-bold text-zinc-300">{item.id.startsWith("builtin-") ? "Base CR Connect" : item.workshop_id ? "Base da oficina" : "Base geral"}</span></div><h3 className="mt-1 font-semibold">{item.title}</h3><p className="mt-2 text-sm leading-6 text-zinc-300">{item.description || "Sem descrição."}</p>{item.possible_causes && <div className="mt-4"><b className="text-sm">Causas possíveis</b><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-zinc-400">{item.possible_causes}</p></div>}{item.recommended_tests && <div className="mt-4 rounded-lg border border-[#6b510d] bg-[#211805] p-3"><b className="text-sm text-[#FFC107]">Testes recomendados</b><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-zinc-300">{item.recommended_tests}</p></div>}</>; }
function TechResult({ item }: { item: Tech }) { return <><div className="flex flex-wrap items-center justify-between gap-2"><b className="text-sm text-[#FFC107]">{item.category}</b>{item.workshop_id && <span className="rounded-full bg-zinc-800 px-3 py-1 text-[11px] font-bold text-zinc-300">Base da oficina</span>}</div><h3 className="mt-2 text-lg font-semibold">{item.title}</h3>{(item.brand || item.model || item.engine) && <p className="mt-1 text-sm text-zinc-300">{[item.brand, item.model, item.engine].filter(Boolean).join(" · ")}</p>}<p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-zinc-300">{item.content}</p>{item.source_url && <a href={item.source_url} target="_blank" rel="noreferrer" className="mt-4 inline-block text-sm font-bold text-[#FFC107]">Abrir fonte técnica ↗</a>}</>; }
