"use client";
import { FormEvent, useState } from "react";

export function DiagnosticAssistant({ mode = "diagnostic" }: { mode?: "diagnostic" | "technical" }) {
  const technical = mode === "technical";
  const [vehicle, setVehicle] = useState(""); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function send(e: FormEvent) { e.preventDefault(); setLoading(true); setError(""); setAnswer(""); const r = await fetch("/api/diagnostico-ia", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ vehicle, symptom: question, mode }) }); const data = await r.json(); if (!r.ok) setError(data.error || "Falha ao consultar o assistente."); else setAnswer(data.answer); setLoading(false); }
  return <div className="grid gap-7 xl:grid-cols-[420px_1fr]"><form onSubmit={send} className="rounded-xl border border-zinc-800 bg-[#1A1A1A] p-5"><h2 className="font-semibold">{technical ? "Consultar procedimento" : "Descreva o caso"}</h2>{technical && <div className="mt-4 grid gap-2"><button type="button" onClick={() => setQuestion("Como desmontar esta peça? Informe a ordem de remoção, parafusos, presilhas e conectores.")} className="rounded-lg border border-[#6a531f] p-3 text-left text-sm font-bold text-[#FFC107]">Desmontagem</button><button type="button" onClick={() => setQuestion("Quais ferramentas são necessárias para este serviço?")} className="rounded-lg border border-[#6a531f] p-3 text-left text-sm font-bold text-[#FFC107]">Ferramentas</button><button type="button" onClick={() => setQuestion("Como montar novamente com segurança? Informe conferências e cuidados.")} className="rounded-lg border border-[#6a531f] p-3 text-left text-sm font-bold text-[#FFC107]">Montagem segura</button></div>}<input className="field mt-4" placeholder="Veículo: marca, modelo, ano e motor" value={vehicle} onChange={(e) => setVehicle(e.target.value)} /><textarea required className="field mt-3 min-h-44" placeholder={technical ? "Ex.: remoção do painel central; onde ficam os parafusos e quais ferramentas usar?" : "Ex.: carro falha ao acelerar, luz da injeção acesa..."} value={question} onChange={(e) => setQuestion(e.target.value)} /><button disabled={loading} className="mt-4 rounded-lg bg-[#FFC107] px-4 py-2 font-bold text-black disabled:opacity-60">{loading ? "Buscando..." : "Buscar procedimento"}</button></form><section className="rounded-xl border border-[#4a3818] bg-[#171717] p-5"><p className="text-xs font-bold tracking-[.16em] text-[#FFC107]">{technical ? "GUIA DE PROCEDIMENTO" : "ANÁLISE ASSISTIDA"}</p>{!answer && !error && <p className="mt-5 text-zinc-400">{technical ? "Informe o veículo e o serviço para receber o roteiro de desmontagem e montagem." : "Informe os sintomas para receber hipóteses e verificações iniciais."}</p>}{error && <p className="mt-5 text-red-300">{error}</p>}{answer && <p className="mt-5 whitespace-pre-wrap leading-7 text-zinc-200">{answer}</p>}<p className="mt-6 border-t border-zinc-800 pt-4 text-xs text-zinc-500">A IA auxilia a consulta, mas não substitui manual técnico nem diagnóstico presencial.</p></section></div>;
}
