"use client";

import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Product = { id: string; code: string | null; description: string; manufacturer: string | null; quantity: number; minimum_quantity: number; sale_price: number; location: string | null };
const blank = { code: "", description: "", manufacturer: "", quantity: "0", minimum_quantity: "0", sale_price: "0", location: "" };

export function InventoryManager({ workshopId }: { workshopId: string }) {
  const db = createClient(); const [items, setItems] = useState<Product[]>([]); const [form, setForm] = useState(blank); const [editing, setEditing] = useState<string | null>(null); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function load() { const { data, error } = await db.from("products").select("id,code,description,manufacturer,quantity,minimum_quantity,sale_price,location").eq("workshop_id", workshopId).order("description"); if (error) setMessage(error.message); else setItems(data as Product[]); }
  useEffect(() => { void load(); }, []);
  function change(key: keyof typeof blank, value: string) { setForm((current) => ({ ...current, [key]: value })); }
  async function save(event: FormEvent) { event.preventDefault(); if (saving) return; setSaving(true); setMessage("Aguarde, salvando o produto…"); const payload = { workshop_id: workshopId, code: form.code || null, description: form.description, manufacturer: form.manufacturer || null, quantity: Number(form.quantity), minimum_quantity: Number(form.minimum_quantity), sale_price: Number(form.sale_price), location: form.location || null }; const result = editing ? await db.from("products").update(payload).eq("id", editing) : await db.from("products").insert(payload); setSaving(false); setMessage(result.error?.message || "Produto salvo."); if (!result.error) { setForm(blank); setEditing(null); void load(); } }
  function select(item: Product) { setEditing(item.id); setForm({ code: item.code || "", description: item.description, manufacturer: item.manufacturer || "", quantity: String(item.quantity), minimum_quantity: String(item.minimum_quantity), sale_price: String(item.sale_price), location: item.location || "" }); }
  return <div className="grid gap-7 xl:grid-cols-[370px_1fr]"><form onSubmit={save} className="rounded-xl border border-zinc-800 bg-[#1A1A1A] p-5"><h2 className="font-semibold">{editing ? "Editar produto" : "Novo produto"}</h2><div className="mt-4 grid gap-3"><input className="field" placeholder="Código" value={form.code} onChange={(e) => change("code", e.target.value)}/><input required className="field" placeholder="Descrição *" value={form.description} onChange={(e) => change("description", e.target.value)}/><input className="field" placeholder="Fabricante" value={form.manufacturer} onChange={(e) => change("manufacturer", e.target.value)}/><div className="grid grid-cols-2 gap-2"><input className="field" type="number" step="0.01" placeholder="Quantidade" value={form.quantity} onChange={(e) => change("quantity", e.target.value)}/><input className="field" type="number" step="0.01" placeholder="Estoque mínimo" value={form.minimum_quantity} onChange={(e) => change("minimum_quantity", e.target.value)}/></div><input className="field" type="number" step="0.01" placeholder="Preço de venda" value={form.sale_price} onChange={(e) => change("sale_price", e.target.value)}/><input className="field" placeholder="Localização" value={form.location} onChange={(e) => change("location", e.target.value)}/></div><button disabled={saving} className="mt-4 rounded-lg bg-[#FFC107] px-4 py-2 font-bold text-black disabled:cursor-wait disabled:opacity-60">{saving ? "Salvando…" : "Salvar produto"}</button>{message && <p className="mt-3 text-sm">{message}</p>}</form><section><h2 className="text-xl font-semibold">Estoque</h2><div className="mt-4 space-y-2">{items.map((item) => <button key={item.id} type="button" disabled={saving} onClick={() => select(item)} className="flex w-full justify-between rounded-xl border border-zinc-800 bg-[#171717] p-4 text-left hover:border-[#FFC107] disabled:opacity-60"><span><b>{item.description}</b><br/><small className="text-zinc-500">{item.code || "Sem código"} · {item.location || "Sem localização"}</small></span><span className={Number(item.quantity) <= Number(item.minimum_quantity) ? "text-red-400" : "text-[#FFC107]"}>{item.quantity} un.<br/><small>R$ {Number(item.sale_price).toFixed(2)}</small></span></button>)}</div></section></div>;
}
