"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { OrderStatusTimeline } from "@/components/order-status-timeline";

type Item = { id: string; kind: string; description: string; quantity: number; unit_price: number; discount: number; product_id: string | null };
type Product = { id: string; description: string; quantity: number; sale_price: number };

export function OrderItemsPanel({ workshopId, orderId, status, onItemsChange }: { workshopId: string; orderId: string; status: string; onItemsChange?: (items: Item[]) => void }) {
  const db = createClient();
  const [items, setItems] = useState<Item[]>([]); const [products, setProducts] = useState<Product[]>([]); const [kind, setKind] = useState("service"); const [description, setDescription] = useState(""); const [productId, setProductId] = useState(""); const [quantity, setQuantity] = useState("1"); const [price, setPrice] = useState("0"); const [message, setMessage] = useState("");
  const total = useMemo(() => items.reduce((sum, item) => sum + Number(item.quantity) * Number(item.unit_price) - Number(item.discount), 0), [items]);
  const money = (value: number) => value.toLocaleString("pt-BR", { minimumFractionDigits: 2, maximumFractionDigits: 2 });

  async function load() { const [a, b] = await Promise.all([db.from("service_order_items").select("id,kind,description,quantity,unit_price,discount,product_id").eq("workshop_id", workshopId).eq("service_order_id", orderId), db.from("products").select("id,description,quantity,sale_price").eq("workshop_id", workshopId).order("description")]); const saved = (a.data || []) as Item[]; setItems(saved); onItemsChange?.(saved); setProducts((b.data || []) as Product[]); }
  useEffect(() => { void load(); }, [orderId]);
  function chooseProduct(id: string) { setProductId(id); const product = products.find((item) => item.id === id); if (product) { setDescription(product.description); setPrice(String(product.sale_price)); } }
  async function add(event: FormEvent) { event.preventDefault(); const product = products.find((item) => item.id === productId); const amount = Number(quantity); if (kind === "part" && !product) { setMessage("Selecione uma peça do estoque."); return; } if (product && amount > Number(product.quantity)) { setMessage(`Estoque insuficiente: disponível ${product.quantity} un.`); return; } const { error } = await db.from("service_order_items").insert({ workshop_id: workshopId, service_order_id: orderId, kind, product_id: kind === "part" ? productId : null, description, quantity: amount, unit_price: Number(price), discount: 0 }); setMessage(error?.message || (kind === "part" ? "Peça adicionada e baixada do estoque." : "Item adicionado.")); if (!error) { setDescription(""); setProductId(""); setQuantity("1"); setPrice("0"); await load(); } }
  async function remove(item: Item) { if (!confirm(`Remover ${item.description}?`)) return; await db.from("service_order_items").delete().eq("id", item.id); await load(); setMessage(item.kind === "part" ? "Peça removida e estoque estornado." : "Item removido."); }

  return <div className="mt-5 rounded-xl border border-[#4c3c1d] bg-black/40 p-4"><p className="text-xs font-bold tracking-[.16em] text-[#FFC107]">ACOMPANHAMENTO DA O.S.</p><OrderStatusTimeline status={status}/><form onSubmit={add} className="mt-5 grid gap-3 border-t border-zinc-800 pt-4"><select className="field" value={kind} onChange={(event) => { setKind(event.target.value); setProductId(""); setDescription(""); }}><option value="service">Serviço</option><option value="part">Peça do estoque</option><option value="labor">Mão de obra</option></select>{kind === "part" ? <select required className="field" value={productId} onChange={(event) => chooseProduct(event.target.value)}><option value="">Selecione a peça *</option>{products.map((product) => <option key={product.id} value={product.id}>{product.description} — {product.quantity} un.</option>)}</select> : <input required className="field" placeholder="Descrição do serviço ou peça" value={description} onChange={(event) => setDescription(event.target.value)} />}<div className="grid grid-cols-2 gap-3"><label className="text-sm text-zinc-300">Quantidade<input required min="0.001" className="field mt-1" type="number" step="0.001" value={quantity} onChange={(event) => setQuantity(event.target.value)} /></label><label className="text-sm text-zinc-300">Valor unitário (R$)<input required min="0" className="field mt-1" type="number" step="0.01" value={price} onChange={(event) => setPrice(event.target.value)} /></label></div><button className="rounded-lg bg-[#FFC107] px-3 py-2 font-bold text-black">Adicionar item</button></form>{message && <p className="mt-3 text-sm text-zinc-300">{message}</p>}<div className="mt-4 space-y-2">{items.map((item) => <div className="flex justify-between rounded-lg bg-zinc-900 p-2 text-sm" key={item.id}><span>{item.description} <em className="text-zinc-500">{item.kind === "part" ? `peça · ${item.quantity} un.` : item.kind}</em></span><span><b>R$ {money(Number(item.quantity) * Number(item.unit_price) - Number(item.discount))}</b><button type="button" onClick={() => void remove(item)} className="ml-3 text-xs text-red-300">Remover</button></span></div>)}</div><p className="mt-4 text-right font-bold text-[#FFC107]">Total da O.S.: R$ {money(total)}</p></div>;
}
