"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Item = { id: string; kind: string; description: string; quantity: number; unit_price: number; discount: number; product_id: string | null };
type Product = { id: string; description: string; quantity: number; sale_price: number };
const timeline = [["open", "Solicitação recebida"], ["diagnosing", "Em diagnóstico"], ["awaiting_approval", "Aguardando aprovação"], ["repairing", "Em manutenção"], ["finished", "Testes realizados"], ["delivered", "Entregue"]] as const;

export function OrderItemsPanel({ workshopId, orderId, status }: { workshopId: string; orderId: string; status: string }) {
  const db = createClient();
  const [items, setItems] = useState<Item[]>([]); const [products, setProducts] = useState<Product[]>([]); const [kind, setKind] = useState("service"); const [description, setDescription] = useState(""); const [productId, setProductId] = useState(""); const [quantity, setQuantity] = useState("1"); const [price, setPrice] = useState("0"); const [message, setMessage] = useState("");
  const total = useMemo(() => items.reduce((sum, item) => sum + Number(item.quantity) * Number(item.unit_price) - Number(item.discount), 0), [items]);
  const statusIndex = status === "awaiting_part" ? 3 : timeline.findIndex(([value]) => value === status);
  async function load() { const [a, b] = await Promise.all([db.from("service_order_items").select("id,kind,description,quantity,unit_price,discount,product_id").eq("workshop_id", workshopId).eq("service_order_id", orderId), db.from("products").select("id,description,quantity,sale_price").eq("workshop_id", workshopId).order("description")]); setItems((a.data || []) as Item[]); setProducts((b.data || []) as Product[]); }
  useEffect(() => { void load(); }, [orderId]);
  function chooseProduct(id: string) { setProductId(id); const product = products.find((item) => item.id === id); if (product) { setDescription(product.description); setPrice(String(product.sale_price)); } }
  async function add(event: FormEvent) { event.preventDefault(); const product = products.find((item) => item.id === productId); const amount = Number(quantity); if (kind === "part" && !product) { setMessage("Selecione uma peça do estoque."); return; } if (product && amount > Number(product.quantity)) { setMessage(`Estoque insuficiente: disponível ${product.quantity} un.`); return; } const { error } = await db.from("service_order_items").insert({ workshop_id: workshopId, service_order_id: orderId, kind, product_id: kind === "part" ? productId : null, description, quantity: amount, unit_price: Number(price), discount: 0 }); setMessage(error?.message || (kind === "part" ? "Peça adicionada e baixada do estoque." : "Item adicionado.")); if (!error) { setDescription(""); setProductId(""); setQuantity("1"); setPrice("0"); await load(); } }
  async function remove(item: Item) { if (!confirm(`Remover ${item.description}?`)) return; await db.from("service_order_items").delete().eq("id", item.id); await load(); setMessage(item.kind === "part" ? "Peça removida e estoque estornado." : "Item removido."); }
  return <div className="mt-5 rounded-xl border border-[#4c3c1d] bg-black/40 p-4"><p className="text-xs font-bold tracking-[.16em] text-[#FFC107]">ACOMPANHAMENTO DA O.S.</p><ol className="mt-4 space-y-0">{timeline.map(([value, label], index) => { const complete = statusIndex >= index; const active = statusIndex === index; return <li key={value} className="grid grid-cols-[28px_1fr] gap-3"><div className="flex flex-col items-center"><span className={`grid h-7 w-7 place-items-center rounded-full text-xs font-bold ${complete ? "bg-[#8bdc45] text-black" : "bg-zinc-600 text-zinc-300"}`}>{complete ? "✓" : index + 1}</span>{index < timeline.length - 1 && <span className={`h-7 w-0.5 ${complete ? "bg-[#8bdc45]" : "bg-zinc-700"}`} />}</div><div className="pt-1"><p className={active ? "font-semibold text-[#FFC107]" : complete ? "text-zinc-200" : "text-zinc-500"}>{label}</p></div></li>; })}</ol><form onSubmit={add} className="mt-5 grid gap-2 border-t border-zinc-800 pt-4"><select className="field" value={kind} onChange={e => { setKind(e.target.value); setProductId(""); setDescription(""); }}><option value="service">Serviço</option><option value="part">Peça do estoque</option><option value="labor">Mão de obra</option></select>{kind === "part" ? <select required className="field" value={productId} onChange={e => chooseProduct(e.target.value)}><option value="">Selecione a peça *</option>{products.map(product => <option key={product.id} value={product.id}>{product.description} — {product.quantity} un.</option>)}</select> : <input required className="field" placeholder="Descrição" value={description} onChange={e => setDescription(e.target.value)} />}<div className="grid grid-cols-2 gap-2"><input required min="0.001" className="field" type="number" step="0.001" placeholder="Quantidade" value={quantity} onChange={e => setQuantity(e.target.value)} /><input className="field" type="number" step="0.01" placeholder="Preço" value={price} onChange={e => setPrice(e.target.value)} /></div><button className="rounded-lg bg-[#FFC107] px-3 py-2 font-bold text-black">Adicionar item</button></form>{message && <p className="mt-3 text-sm text-zinc-300">{message}</p>}<div className="mt-4 space-y-2">{items.map(item => <div className="flex justify-between rounded-lg bg-zinc-900 p-2 text-sm" key={item.id}><span>{item.description} <em className="text-zinc-500">{item.kind === "part" ? `peça · ${item.quantity} un.` : item.kind}</em></span><span><b>R$ {(Number(item.quantity) * Number(item.unit_price) - Number(item.discount)).toFixed(2)}</b><button onClick={() => void remove(item)} className="ml-3 text-xs text-red-300">Remover</button></span></div>)}</div><p className="mt-4 text-right font-bold text-[#FFC107]">Total da O.S.: R$ {total.toFixed(2)}</p></div>;
}
