"use client";

import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Thread = { client_id: string; workshop_id: string; client_name: string; workshop_name: string };
type Message = { id: string; body: string; created_at: string; owner_id: string | null };

export function OwnerChatManager({ userId }: { userId: string }) {
  const db = createClient();
  const [threads, setThreads] = useState<Thread[]>([]); const [thread, setThread] = useState<Thread | null>(null);
  const [messages, setMessages] = useState<Message[]>([]); const [body, setBody] = useState(""); const [notice, setNotice] = useState(""); const [sending, setSending] = useState(false);
  async function loadThreads() { const { data, error } = await db.rpc("get_owner_chat_threads"); if (error) { setNotice(error.message); return; } const items = (data || []) as Thread[]; setThreads(items); setThread((current) => current || items[0] || null); }
  async function loadMessages(selected = thread) { if (!selected) { setMessages([]); return; } const { data, error } = await db.from("messages").select("id,body,created_at,owner_id").eq("client_id", selected.client_id).order("created_at", { ascending: true }); if (error) setNotice(error.message); else setMessages((data || []) as Message[]); }
  useEffect(() => { void loadThreads(); }, []);
  useEffect(() => { void loadMessages(); const timer = window.setInterval(() => void loadMessages(), 7000); return () => window.clearInterval(timer); }, [thread?.client_id]);
  async function send(event: FormEvent) { event.preventDefault(); if (!thread || !body.trim()) return; setSending(true); setNotice(""); const { data, error } = await db.from("messages").insert({ workshop_id: thread.workshop_id, client_id: thread.client_id, sender_id: userId, owner_id: userId, body: body.trim() }).select("id").single(); if (error) setNotice(error.message); else { setBody(""); setNotice("Mensagem enviada para a oficina."); await loadMessages(thread); void fetch("/api/push-order", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: data.id, event: "chat" }) }); } setSending(false); }
  return <div className="mx-auto max-w-4xl px-5 pb-12 text-zinc-100 md:px-10"><a href="/app" className="text-sm font-bold text-[#FFC107]">← Voltar</a><p className="mt-6 text-xs font-black tracking-[.2em] text-[#FFC107]">ATENDIMENTO</p><h1 className="mt-2 text-3xl font-black">Mensagens</h1><p className="mt-2 text-zinc-400">Converse diretamente com a sua oficina.</p>{threads.length > 1 && <select className="field mt-5" value={thread?.client_id || ""} onChange={(event) => setThread(threads.find((item) => item.client_id === event.target.value) || null)}>{threads.map((item) => <option key={item.client_id} value={item.client_id}>{item.workshop_name} · {item.client_name}</option>)}</select>}{!thread ? <section className="mt-7 rounded-2xl border border-zinc-800 bg-[#171717] p-5 text-zinc-400">Ainda não há uma conversa vinculada à sua conta. Peça para a oficina cadastrar seu cliente usando este mesmo e-mail.</section> : <section className="mt-7 rounded-2xl border border-zinc-800 bg-[#171717] p-5"><div className="border-b border-zinc-800 pb-4"><b>{thread.workshop_name}</b><p className="mt-1 text-sm text-zinc-400">Conversa sobre o cliente {thread.client_name}</p></div><div className="min-h-64 space-y-3 py-5">{messages.length === 0 && <p className="text-sm text-zinc-400">Envie uma mensagem para iniciar a conversa.</p>}{messages.map((message) => <div key={message.id} className={`max-w-[85%] rounded-2xl p-4 ${message.owner_id ? "ml-auto bg-[#FFC107] text-black" : "bg-zinc-800 text-zinc-100"}`}><p>{message.body}</p><time className={`mt-2 block text-xs ${message.owner_id ? "text-black/70" : "text-zinc-400"}`}>{new Date(message.created_at).toLocaleString("pt-BR")}</time></div>)}</div><form onSubmit={send} className="border-t border-zinc-800 pt-4"><textarea required value={body} onChange={(event) => setBody(event.target.value)} maxLength={1000} className="field min-h-28" placeholder="Escreva sua mensagem para a oficina..."/><button disabled={sending} className="mt-3 rounded-xl bg-[#FFC107] px-5 py-3 font-black text-black disabled:opacity-60">{sending ? "Enviando..." : "Enviar mensagem"}</button>{notice && <p role="status" className="mt-3 text-sm text-[#FFC107]">{notice}</p>}</form></section>}</div>;
}
