"use client";

import { useState } from "react";

type Term = { token: string; client_name: string; vehicle_label: string | null; service_description: string | null; part_description: string; status: string; accepted_at: string | null; rejected_at: string | null };

export function PublicTermResponse({ term }: { term: Term }) {
  const [read, setRead] = useState(false); const [sending, setSending] = useState(false); const [status, setStatus] = useState(term.status); const [message, setMessage] = useState("");
  async function respond(response: "accepted" | "rejected") { if (sending || (response === "accepted" && !read)) return; setSending(true); setMessage("Registrando sua resposta…"); const result = await fetch(`/api/termos/${term.token}/responder`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ response }) }); const data = await result.json(); setSending(false); if (!result.ok) { setMessage(data.error || "Não foi possível registrar sua resposta."); return; } setStatus(data.status); setMessage(response === "accepted" ? "Termo aceito com sucesso. A oficina foi avisada." : "Recusa registrada. A oficina foi avisada."); }
  if (status === "accepted") return <main className="min-h-screen bg-[#101010] px-5 py-12 text-zinc-100"><section className="mx-auto max-w-xl rounded-2xl border border-emerald-700/60 bg-[#171717] p-7 text-center"><p className="text-sm font-bold tracking-[.2em] text-[#FFC107]">CR CONNECT</p><h1 className="mt-4 text-3xl font-bold text-emerald-400">Termo aceito</h1><p className="mt-4 leading-7 text-zinc-300">Sua confirmação foi registrada com data e hora. A oficina já foi avisada.</p></section></main>;
  if (status === "rejected") return <main className="min-h-screen bg-[#101010] px-5 py-12 text-zinc-100"><section className="mx-auto max-w-xl rounded-2xl border border-red-700/60 bg-[#171717] p-7 text-center"><p className="text-sm font-bold tracking-[.2em] text-[#FFC107]">CR CONNECT</p><h1 className="mt-4 text-3xl font-bold text-red-300">Termo recusado</h1><p className="mt-4 leading-7 text-zinc-300">Sua recusa foi registrada. A oficina foi avisada para conversar com você.</p></section></main>;
  return <main className="min-h-screen bg-[#101010] px-5 py-8 text-zinc-100"><section className="mx-auto max-w-2xl rounded-2xl border border-[#6b510d] bg-[#171717] p-6 sm:p-9"><p className="text-xs font-bold tracking-[.22em] text-[#FFC107]">CR CONNECT · CR REPARADOR AUTOMOTIVO</p><h1 className="mt-3 text-3xl font-bold">Termo de responsabilidade</h1><p className="mt-2 text-zinc-400">Peça fornecida pelo cliente</p><div className="mt-7 rounded-xl border border-zinc-700 bg-black/20 p-4 text-sm"><p><b>Cliente:</b> {term.client_name}</p>{term.vehicle_label && <p className="mt-2"><b>Veículo:</b> {term.vehicle_label}</p>}{term.service_description && <p className="mt-2"><b>Serviço:</b> {term.service_description}</p>}<p className="mt-2"><b>Peça fornecida:</b> {term.part_description}</p></div><article className="mt-6 space-y-4 text-[15px] leading-7 text-zinc-200"><p><b>1.</b> Declaro que a peça informada acima foi adquirida e fornecida por mim, por livre escolha, podendo ser diferente da marca, modelo, procedência ou especificação recomendada pela oficina.</p><p><b>2.</b> Estou ciente de que a oficina não controla a origem, autenticidade, qualidade, compatibilidade, armazenamento ou garantia comercial da peça fornecida pelo cliente.</p><p><b>3.</b> Autorizo a instalação e assumo responsabilidade por defeitos, falhas, mau funcionamento, desgaste ou danos decorrentes da própria peça ou de sua incompatibilidade com o veículo.</p><p><b>4.</b> A garantia da oficina não cobre a peça fornecida pelo cliente nem problemas causados por ela. A mão de obra somente poderá ser analisada se houver defeito comprovadamente exclusivo no serviço executado, sem relação com a peça.</p><p><b>5.</b> Se for necessário desmontar, substituir novamente ou realizar serviços adicionais por falha ou incompatibilidade da peça, haverá nova cobrança de mão de obra, peças e despesas necessárias.</p></article><label className="mt-7 flex gap-3 rounded-xl border border-[#6b510d] bg-[#211805] p-4 text-sm"><input type="checkbox" checked={read} onChange={(event) => setRead(event.target.checked)} className="mt-1 h-5 w-5 accent-[#FFC107]"/><span>Li todo o termo, compreendi as condições e concordo em assumir a responsabilidade pela peça fornecida.</span></label><div className="mt-5 grid gap-3 sm:grid-cols-2"><button disabled={!read || sending} onClick={() => void respond("accepted")} className="rounded-xl bg-[#FFC107] px-4 py-3 font-bold text-black disabled:cursor-not-allowed disabled:opacity-50">{sending ? "Aguarde…" : "Aceitar termo"}</button><button disabled={sending} onClick={() => void respond("rejected")} className="rounded-xl border border-red-500/70 px-4 py-3 font-bold text-red-300 disabled:opacity-50">Recusar</button></div>{message && <p className="mt-4 rounded-lg bg-black/30 p-3 text-sm text-[#FFC107]">{message}</p>}</section></main>;
}
