"use client";
import { useEffect, useState } from "react";
function key(value: string) { const encoded = value.replace(/-/g, "+").replace(/_/g, "/") + "=".repeat((4 - value.length % 4) % 4); return Uint8Array.from(atob(encoded), (c) => c.charCodeAt(0)); }
export function PushNotificationSetup() {
  const [enabled, setEnabled] = useState(false); const [status, setStatus] = useState("");
  useEffect(() => { let active = true; async function check() { if (!("serviceWorker" in navigator) || !("PushManager" in window)) return; const registration = await navigator.serviceWorker.getRegistration("/"); const subscription = await registration?.pushManager.getSubscription(); if (active && subscription) setEnabled(true); } void check(); return () => { active = false; }; }, []);
  async function enable() { const publicKey = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY; if (!publicKey || !("serviceWorker" in navigator) || !("PushManager" in window)) { setStatus("Avisos push ainda estao sendo preparados."); return; } const permission = await Notification.requestPermission(); if (permission !== "granted") { setStatus("Permita as notificacoes para receber alertas."); return; } const registration = await navigator.serviceWorker.register("/sw.js"); const existing = await registration.pushManager.getSubscription(); const subscription = existing || await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: key(publicKey) }); const response = await fetch("/api/push-subscriptions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(subscription) }); if (response.ok) { setEnabled(true); setStatus("Avisos push ativados neste celular."); } else setStatus("Nao foi possivel ativar agora."); }
  if (enabled) return null;
  return <div className="fixed bottom-5 left-5 z-40 max-w-xs"><button type="button" onClick={() => void enable()} className="rounded-xl border border-[#FFC107] bg-[#171717] px-4 py-3 text-sm font-bold text-[#FFC107] shadow-xl">Ativar notificacoes mesmo fechado</button>{status && <p className="mt-2 rounded-lg bg-black/80 p-2 text-xs text-zinc-200">{status}</p>}</div>;
}
