"use client";

import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { OrderItemsPanel } from "@/components/order-items-panel";
import { PrintDocument } from "@/components/print-document";
import { AttachmentsManager } from "@/components/attachments-manager";

type Client = { id: string; full_name: string }; type Vehicle = { id: string; client_id: string; brand: string; model: string; plate: string | null }; type Order = { id: string; number: number; client_id: string; vehicle_id: string; status: string; customer_complaint: string; diagnosis: string | null; notes: string | null; clients: Client | null; vehicles: Vehicle | null }; type OrderItem = { description: string; quantity: number; unit_price: number; discount: number };
const states = [["open", "Aberta"], ["diagnosing", "Em diagnóstico"], ["awaiting_approval", "Aguardando aprovação"], ["awaiting_part", "Aguardando peça"], ["repairing", "Em reparo"], ["finished", "Finalizada"], ["delivered", "Entregue"], ["cancelled", "Cancelada"]];

export function ServiceOrdersManager({ workshopId }: { workshopId: string }) {
  const db = createClient(); const [clients, setClients] = useState<Client[]>([]); const [vehicles, setVehicles] = useState<Vehicle[]>([]); const [orders, setOrders] = useState<Order[]>([]); const [selected, setSelected] = useState<Order | null>(null); const [orderItems, setOrderItems] = useState<OrderItem[]>([]); const [client, setClient] = useState(""); const [vehicle, setVehicle] = useState(""); const [status, setStatus] = useState("open"); const [complaint, setComplaint] = useState(""); const [diagnosis, setDiagnosis] = useState(""); const [note, setNote] = useState(""); const [message, setMessage] = useState("");
  async function load() { const [a, b, c] = await Promise.all([db.from("clients").select("id,full_name").eq("workshop_id", workshopId), db.from("vehicles").select("id,client_id,brand,model,plate").eq("workshop_id", workshopId), db.from("service_orders").select("id,number,client_id,vehicle_id,status,customer_complaint,diagnosis,notes,clients(id,full_name),vehicles(id,client_id,brand,model,plate)").eq("workshop_id", workshopId).order("opened_at", { ascending: false })]); setClients((a.data || []) as Client[]); setVehicles((b.data || []) as Vehicle[]); setOrders((c.data || []) as unknown as Order[]); }
  useEffect(() => { load(); }, []); const allowed = vehicles.filter(item => item.client_id === client);
  async function save(e: FormEvent) { e.preventDefault(); const payload = { workshop_id: workshopId, client_id: client, vehicle_id: vehicle, status, customer_complaint: complaint, diagnosis: diagnosis || null, notes: note || null }; const result = selected ? await db.from("service_orders").update(payload).eq("id", selected.id) : await db.from("service_orders").insert(payload); setMessage(result.error?.message || "O.S. salva. Você continua nesta tela para fazer outras alterações."); if (!result.error) await load(); }
  async function edit(order: Order) { setSelected(order); setClient(order.client_id); setVehicle(order.vehicle_id); setStatus(order.status); setComplaint(order.customer_complaint); setDiagnosis(order.diagnosis || ""); setNote(order.notes || ""); const { data } = await db.from("service_order_items").select("description,quantity,unit_price,discount").eq("workshop_id", workshopId).eq("service_order_id", order.id); setOrderItems((data || []) as OrderItem[]); }
  return <div className="grid gap-7 xl:grid-cols-[390px_1fr]"><form onSubmit={save} className="rounded-xl border border-zinc-800 bg-[#1A1A1A] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-semibold">{selected ? `O.S. #${selected.number}` : "Nova O.S."}</h2>{selected && <PrintDocument type="Ordem de Serviço" number={`#${selected.number}`} client={selected.clients?.full_name || "Cliente"} vehicle={`${selected.vehicles?.brand || ""} ${selected.vehicles?.model || ""} ${selected.vehicles?.plate || ""}`} status={states.find(item => item[0] === status)?.[1] || status} note={note || complaint} items={orderItems} />}</div><div className="mt-4 grid gap-3"><select required className="field" value={client} onChange={e => { setClient(e.target.value); setVehicle(""); }}><option value="">Cliente *</option>{clients.map(item => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select><select required className="field" disabled={!client} value={vehicle} onChange={e => setVehicle(e.target.value)}><option value="">Veículo *</option>{allowed.map(item => <option key={item.id} value={item.id}>{item.brand} {item.model} {item.plate ? `(${item.plate})` : ""}</option>)}</select><select className="field" value={status} onChange={e => setStatus(e.target.value)}>{states.map(item => <option key={item[0]} value={item[0]}>{item[1]}</option>)}</select><textarea required className="field min-h-24" placeholder="Reclamação do cliente" value={complaint} onChange={e => setComplaint(e.target.value)} /><textarea className="field" placeholder="Diagnóstico" value={diagnosis} onChange={e => setDiagnosis(e.target.value)} /><textarea className="field" placeholder="Observações" value={note} onChange={e => setNote(e.target.value)} /></div><div className="mt-4 flex flex-wrap gap-3"><button className="rounded-lg bg-[#FFC107] px-4 py-2 font-bold text-black">Salvar O.S.</button><a href="/app" className="rounded-lg border border-zinc-600 px-4 py-2 font-bold text-zinc-100">Voltar ao menu</a></div>{message && <p className="mt-3 text-sm text-[#FFC107]">{message}</p>}{selected && <><OrderItemsPanel workshopId={workshopId} orderId={selected.id} status={status} /><AttachmentsManager workshopId={workshopId} orderId={selected.id} /></>}</form><section><h2 className="text-xl font-semibold">Ordens de serviço</h2><div className="mt-4 space-y-2">{orders.map(order => <button key={order.id} onClick={() => void edit(order)} className="flex w-full justify-between rounded-xl border border-zinc-800 bg-[#171717] p-4 text-left hover:border-[#FFC107]"><span><b>#{order.number}</b> · {order.clients?.full_name}<br /><small className="text-zinc-500">{order.vehicles?.brand} {order.vehicles?.model} · {order.vehicles?.plate || "sem placa"}</small></span><b className="text-[#FFC107]">{states.find(item => item[0] === order.status)?.[1]}</b></button>)}</div></section></div>;
}
