"use client";

import { divIcon } from "leaflet";
import { MapContainer, Marker, Popup, TileLayer } from "react-leaflet";

export type SosMapWorkshop = { id: string; name: string; whatsapp: string | null; latitude: number; longitude: number; emergency_services: string[]; emergency_radius_km: number; distance?: number };

const workshopIcon = divIcon({ className: "", html: '<div style="display:grid;place-items:center;width:42px;height:42px;border-radius:50% 50% 50% 0;transform:rotate(-45deg);background:#FFC107;border:3px solid #171717;box-shadow:0 3px 10px #000;color:#111;font-weight:900;font-family:Arial"><span style="transform:rotate(45deg);font-size:12px">CR</span></div>', iconSize: [42, 42], iconAnchor: [21, 42], popupAnchor: [0, -38] });
const userIcon = divIcon({ className: "", html: '<div style="width:19px;height:19px;border-radius:50%;background:#2d8cff;border:3px solid #fff;box-shadow:0 2px 8px #000"></div>', iconSize: [19, 19], iconAnchor: [9, 9] });

export function SosMap({ position, workshops, onChoose }: { position: { latitude: number; longitude: number }; workshops: SosMapWorkshop[]; onChoose: (workshop: SosMapWorkshop) => void }) {
  return <section className="mt-6 overflow-hidden rounded-2xl border border-[#5a4a24] bg-[#171717]"><div className="border-b border-zinc-800 px-4 py-3"><p className="font-bold text-[#FFC107]">Mapa CR SOS</p><p className="mt-1 text-sm text-zinc-400">Toque no marcador dourado para escolher uma oficina.</p></div><MapContainer center={[position.latitude, position.longitude]} zoom={13} scrollWheelZoom className="cr-sos-map h-[330px] w-full"><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><Marker position={[position.latitude, position.longitude]} icon={userIcon}><Popup>Você está aqui</Popup></Marker>{workshops.map((workshop) => <Marker key={workshop.id} position={[Number(workshop.latitude), Number(workshop.longitude)]} icon={workshopIcon}><Popup><div><strong>{workshop.name}</strong><br /><span style={{ color: "#a1a1aa", fontSize: 12 }}>{workshop.emergency_services.join(" · ")}</span>{typeof workshop.distance === "number" && <p style={{ color: "#FFC107", margin: "8px 0", fontWeight: 700 }}>{workshop.distance.toFixed(1)} km de você</p>}<button type="button" onClick={() => onChoose(workshop)} style={{ background: "#FFC107", color: "#111", border: 0, borderRadius: 7, padding: "8px 10px", fontWeight: 700, cursor: "pointer" }}>Pedir ajuda</button><a href={`https://www.google.com/maps/dir/?api=1&destination=${workshop.latitude},${workshop.longitude}`} target="_blank" rel="noreferrer" style={{ display: "inline-block", marginLeft: 8, color: "#FFC107", fontWeight: 700 }}>Rota</a></div></Popup></Marker>)}</MapContainer></section>;
}
