"use client";

import { FormEvent, useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Member = { user_id: string; role: string }; type Profile = { id: string; full_name: string | null }; type Invite = { id: string; email: string; role: string; accepted_at: string | null; created_at: string };
const roles = [["admin", "Administrador"], ["mechanic", "Mecânico"], ["attendant", "Atendimento"], ["inventory", "Estoque"]];

export function TeamManager({ workshopId, isAdmin }: { workshopId: string; isAdmin: boolean }) {
  const db = createClient(); const [members, setMembers] = useState<Member[]>([]); const [profiles, setProfiles] = useState<Profile[]>([]); const [invites, setInvites] = useState<Invite[]>([]); const [email, setEmail] = useState(""); const [role, setRole] = useState("mechanic"); const [message, setMessage] = useState("");
  async function load() { const [memberResult, profileResult, inviteResult] = await Promise.all([db.from("workshop_users").select("user_id,role").eq("workshop_id", workshopId), db.from("profiles").select("id,full_name"), db.from("team_invites").select("id,email,role,accepted_at,created_at").eq("workshop_id", workshopId).order("created_at", { ascending: false })]); setMembers((memberResult.data || []) as Member[]); setProfiles((profileResult.data || []) as Profile[]); setInvites((inviteResult.data || []) as Invite[]); }
  useEffect(() => { load(); }, []);
  async function invite(e: FormEvent) { e.preventDefault(); const { error } = await db.from("team_invites").insert({ workshop_id: workshopId, email: email.trim().toLowerCase(), role, invited_by: (await db.auth.getUser()).data.user?.id }); setMessage(error?.message || "Convite registrado. A pessoa deve entrar no CR Connect com este mesmo e-mail para ativar o acesso."); if (!error) { setEmail(""); setRole("mechanic"); load(); } }
  async function changeRole(userId: string, nextRole: string) { const { error } = await db.from("workshop_users").update({ role: nextRole }).eq("workshop_id", workshopId).eq("user_id", userId); setMessage(error?.message || "Função atualizada."); load(); }
  const profileName = (id: string) => profiles.find(profile => profile.id === id)?.full_name || "Usuário";
  return <div className="grid gap-7 xl:grid-cols-[360px_1fr]">{isAdmin ? <form onSubmit={invite} className="rounded-xl border border-zinc-800 bg-[#1A1A1A] p-5"><h2 className="font-semibold">Convidar integrante</h2><p className="mt-2 text-sm text-zinc-400">O acesso será ativado automaticamente quando a pessoa entrar usando o e-mail convidado.</p><input required type="email" className="field mt-4" placeholder="email@exemplo.com" value={email} onChange={e => setEmail(e.target.value)} /><select className="field mt-3" value={role} onChange={e => setRole(e.target.value)}>{roles.map(item => <option key={item[0]} value={item[0]}>{item[1]}</option>)}</select><button className="mt-4 rounded-lg bg-[#FFC107] px-4 py-2 font-bold text-black">Registrar convite</button>{message && <p className="mt-3 text-sm text-zinc-300">{message}</p>}<h3 className="mt-7 font-semibold">Convites</h3><div className="mt-3 space-y-2">{invites.length === 0 && <p className="text-sm text-zinc-500">Nenhum convite pendente.</p>}{invites.map(invite => <div key={invite.id} className="rounded-lg border border-zinc-800 p-3 text-sm"><b className="block truncate">{invite.email}</b><span className="text-zinc-500">{roles.find(item => item[0] === invite.role)?.[1]} · {invite.accepted_at ? "Ativado" : "Aguardando acesso"}</span></div>)}</div></form> : <div className="rounded-xl border border-zinc-800 bg-[#1A1A1A] p-5 text-zinc-400">Somente administradores podem convidar pessoas ou alterar permissões.</div>}<section><h2 className="text-xl font-semibold">Equipe da oficina</h2><div className="mt-4 space-y-3">{members.map(member => <article key={member.user_id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-zinc-800 bg-[#171717] p-4"><div><b>{profileName(member.user_id)}</b><p className="mt-1 text-sm text-zinc-500">Acesso ativo</p></div>{isAdmin ? <select className="field w-44" value={member.role} onChange={e => changeRole(member.user_id, e.target.value)}>{roles.map(item => <option key={item[0]} value={item[0]}>{item[1]}</option>)}</select> : <span className="text-sm text-[#FFC107]">{roles.find(item => item[0] === member.role)?.[1]}</span>}</article>)}</div></section></div>;
}
